# Generated by Django 2.2.4 on 2022-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default='book discription'),
        ),
    ]
